### ISSUE TITLE
Why is Newsmax blocked?

### ISSUE THREAD

**Issue by ghost** [rimu/no-qanon#11]
What does Newsmax have to do with QAnon? It certainly isn't far-right, conspiracy, Nazi related, or fake news. This is a site with a moderate Right/Conservative bias (in terms of U.S. politics).

> A Dec. 2019 editorial review of Newsmax's web content determined the site has a Lean Right bias. AllSides now rates Newsmax's opinion section separately, as its bias differs significantly from its news section. Prior to Dec. 2019, AllSides rated Newsmax overall as Right. While Newsmax publishes a magazine, AllSides provides media bias ratings for web content only.

> During our Dec. 2019 editorial review, a multipartisan team of reviewers found Newsmax's bias mostly lies in its story choice, primarily featuring stories that are generally of interest to conservatives. However, as the time of review, Newsmax did feature some stories that may be of interest to those on the left, such as a story about Michelle Obama praising Greta Thunberg. Our reviewers evaluated the types of bias Newsmax displays and found the outlet does not add a lot of spin to its stories nor is its word choice sensationalist; Newsmax's bias largely lies in its story choice. Notably, the site features a substantial amount of news reports from wire sources AllSides rates as Center, such as Reuters and the Associated Press. 

Source: `https://www.allsides.com/news-source/newsmax`

**Comment by rimu** [comment]
Newsmax CEO: "We have an editorial policy of being supportive of the President and his policies" he also says that the President’s lies are "great for news."- https://www.newyorker.com/news/q-and-a/why-newsmax-supports-trumps-false-voter-fraud-claims

Also see
https://en.wikipedia.org/wiki/Newsmax#News_integrity_issues

**Comment by Cybo1927** [comment]
> https://www.newyorker.com/news/q-and-a/why-newsmax-supports-trumps-false-voter-fraud-claims
1. The New Yorker has a hard Left leaning: https://www.allsides.com/news-source/new-yorker
2. If voter fraud is completely false why is the FBI investigating it (https://www.youtube.com/watch?v=4zAPE4GuHZY) and why did a PA USPS worker claim supervisors ordered him to collect and submit ballots that would later be backdated (https://americanmilitarynews.com/2020/11/videos-pa-usps-carrier-denies-recanting-voter-fraud-affidavit-says-he-was-pressured-by-feds/)?  
3. The 'great for news' thing is better with the full context:
>But that’s something that journalists could investigate, rather than making broad claims about it.

>Yeah. Well, I think before we even make the claim, we should say, “Hey, look at this anomaly. Why is this the case?” And we start asking about it. But you know what? At the end of the day, it’s great for news. The news cycle is red-hot, and Newsmax is getting one million people per minute, according to Nielsen, tuning into Newsmax TV. I think it’s good.

>I think you made very clear what you’re saying there.

>Well, I believe that Donald Trump’s been great for the news business. And I think there’s nothing wrong in saying that.

"we should say, “Hey, look at this anomaly. Why is this the case?” And we start asking about it. But you know what? At the end of the day, it’s great for news." shows that, yes, they do publish the thing Trump says because it's great for news. But, That doesn't make them any different than the news/politics sites that also write about how bad they believe Trump is. This is simply related to the biases of the news sites and nothing can fully avoid that, meaning it provides no reason to block it.

4. The "We have an editorial policy of being supportive of the President and his policies" part that you quoted is also important with the context around it. He was being facetious trying to claim his news organization is better than Fox News.

>You have said that you think Fox News was inconsistent in its support of Trump during the past four years. How so? And do you think that being unwavering in support of either Donald Trump or the Republican Party is important to conservative media?

>I think it’s been inconsistent, and I would say it’s been schizophrenic. It, at times, is very supportive, almost to the point you would say of maybe drinking the Kool-Aid, on their opinion shows, and then, on the weekends, extremely hostile. And I think what Newsmax has done has been fairly consistent. We have an editorial policy of being supportive of the President and his policies, but I think if you looked at our digital coverage, for instance, it’s always been very balanced and fair.

>You have shot down this idea of Newsmax becoming Trump TV. Would you want to have the President on as a contributor? What role do you see Trump playing?

>Well, he’s an omnivore when it comes to media. He loves all media. There’s no differentiation. He likes to be on all platforms. He did exceedingly well before he became President using all these platforms. I think he probably expects that he’ll be able to do that once he leaves. So I don’t see him tethered or tied down with any one media, and that’s why I don’t think he’s going to say, “O.K., I’m going to make Newsmax my mouthpiece or my platform.” Nor would we find that a good idea, either. I built a solid news organization over twenty years, and we estimate we reach over thirty million Americans each month through all our different outlets.

<hr>

> https://en.wikipedia.org/wiki/Newsmax#News_integrity_issues

Only one of these under reception is relevant because most are very old and it's a centre-Left labeling Newsmax and some other sites as far-right or fringe then talking about why the media landscape is changing under the Trump presidency. They have no evidence to show that Newsmax is in any way right-wing.

> A Dec. 2019 editorial review of Newsmax's web content determined the site has a Lean Right bias. AllSides now rates Newsmax's opinion section separately, as its bias differs significantly from its news section. Prior to Dec. 2019, AllSides rated Newsmax overall as Right. While Newsmax publishes a magazine, AllSides provides media bias ratings for web content only.

https://www.allsides.com/news-source/newsmax

^ This also applies to the "News integrity issues".
