### ISSUE TITLE
Integrate antifa-n list to your

### ISSUE THREAD

**Issue by ghost** [rimu/no-qanon#17]
I have checked : https://github.com/antifa-n/pihole/blob/master/blocklist.txt, 
Like you propose on your readme file, but it seem it not maintained (or at least updated as many as yours), 
i think i can be a good idea to integrate (and dedup) this list (who has not been updated since 10 months to your).

I'm not sure it's what you want it's why i open an issue and not a pull request.

**Comment by rimu** [comment]
I am hesitant to blindly copy & paste that list because 

- very many of them are non-english and even if I google translate the pages my knowledge of European politics is very low. As such I am often unable to verify their fashiness.
- the author has followed a policy of listing various technical subdomains like webmail.psl.org.br or mail.rep.de which is not really what I want.

Going through it manually and picking out individual sites would be a rich vein to mine but quite time consuming.

**Comment by ghost** [comment]
ok i will close it's true and now that i search more, i don't even know if he have whitelist some so in fact it's a bad idea

**Comment by ghost** [comment]
in fact after a scan with my own search script i have found that he also have tld who does not exist like orgp, za, ...

**Comment by rimu** [comment]
Over the last few days I've coded a specialized CMS for managing the blocklist. It will be deployed in the next couple of days, I just need to add some better security... With this tool you will be able to submit any url and it'll automatically discard any duplicates.
