### ISSUE TITLE
unblock epik.com

### ISSUE THREAD

**Issue by trashman9000** [rimu/no-qanon#44]
Although `epik.com` provides domain registration and hosting services to some websites that are blocked here, it shouldn't be listed as they provide services equally to anyone (they are not an exclusive qanon-only service provider).

**Comment by rimu** [comment]
[No](https://en.wikipedia.org/wiki/Epik_(company)).

**Comment by trashman9000** [comment]
It's a poor inclusion for this list, as visiting epik.com yields nothing related to qanon. Unless this list is also in the business of boycotting, it should just keep the qanon garbage out from the browser.

**Comment by rimu** [comment]
Ah, I think there might have been a misunderstanding.

Despite the 'no-qanon' in the name, this list has a broader reach: "A blocklist for QAnon, conspiracy, fake news, nazi websites." You see, QAnon is just a small part of a broader fascist movement. Conspiracy theories are necessary to the growth of fascism because it weakens trust (in institutions and interpersonal) and destroys truth, reason, respect for expertise. Here is a diagram I made, showing where conspiracy theories fit into the wider structure/strategy. ![how fascism works](https://user-images.githubusercontent.com/3310831/178208614-acfddb04-ac43-4171-a6cf-4fd6e7286eeb.png). See the top right.

Epik is a big node in the alt-right fascist network and as such deserves to be on this list. I would also seriously consider adding every customer of theirs to the list as they are contributing to the upkeep of the fascist movement infrastructure, making them complicit. 

Back when Epik was hacked I went through some of the domain names that were leaked and added anything especially interesting. This is the commit: https://github.com/rimu/no-qanon/commit/179a25a3d39d66831ad7af4121a2590087551e9a 

As you can see I've put some thought and effort into this. It is unlikely that I will be changing my position on it.

**Comment by trashman9000** [comment]
>  I would also seriously consider adding every customer of theirs to the list as they are contributing to the upkeep of the fascist movement infrastructure, making them complicit.

I wouldn't recommend it. 

A while ago I was searching for a registrar and a few netizens (some even stating that they don't share the same opinions from its CEO which made me look them up in wikipedia first) were recommending epik as a better/safer registrar in regards to them being much more stringent in handling complaints (such as DMCA requests) and client data (some registrars have been known to be lax in this regard and revealed PII info to what turned out to be bogus legal requests).
It seems that a subset of clients (of unknown size) choose epik specifically for PII reasons (no one likes being doxxed) or as protection against chilling effects/SLAPP.

This supposed extra scrutiny I guess is one "positive side-effect" given their placement in your diagram as I'm sure there are loads of people who'd pretty much prefer for these qanon websites to have never existed at all and some dedicated individuals who will try to actively dismantle them by any means.

> As you can see I've put some thought and effort into this. It is unlikely that I will be changing my position on it.

You've clearly done more research into this topic more than I did so I won't discount your effort on it. When I asked you to reconsider the inclusion it was mostly due to the reason explained above. Personally I treat qanon content the same as spam, to be blocked since I'm not interested in reading it (which turns out to be nonsense almost all the time).

**Comment by rimu** [comment]
Those are not just "the CEO's opinions" - that infrastructure was [created by fascists to advance the fascist cause](https://archive.ph/traih). People who knowingly recommend, use and pay for fascist infrastructure run the risk of being assumed to be fascists and all the consequences of that. Just like those who [march alongside fascists](https://theconversation.com/the-extremism-visible-at-the-parliament-protest-has-been-growing-in-nz-for-years-is-enough-being-done-177831) or [drink at a bar with fascists](https://www.reddit.com/r/TalesFromYourServer/comments/hsiisw/kicking_a_nazi_out_as_soon_as_they_walk_in/).
