### ISSUE TITLE
t.me blocked?

### ISSUE THREAD

**Issue by ghost** [rimu/no-qanon#50]
Hi, first of all thank you very much for your hard work <3

I just noticed that the host `t.me` is blocked and I wanted to know if this was a false positive or if it was intentional (since QAnon groups are pretty active on Telegram). I was unsure, since other Telegram hosts are not blocked?

The line in question: https://github.com/rimu/no-qanon/blob/a9ad6c4c7e4827ecac551147d7152c19ee7d5ec3/dnsmasq_hosts.txt#LL820C1-L820C22

**Comment by rimu** [comment]
Yes, that was intentional.

t.me is used as a way to onboard new victims into radicalization groups in Telegram. However I didn't want to go down the path of blocking Telegram entirely.

Telegram's goals seem to be pretty vanilla. They are totally negligent in moderation but as far as I know not intentionally fascist or overtly promoting conspiracy content. In contrast, gab or truth social are clearly over the line.

There exist other blocklists for specific apps. I don't have them at my fingertips at the moment but it'd be good to link to them in the README as additional resources, sometime.

**Comment by ghost** [comment]
Oh okay, thanks for the answer! It's true, I remember seeing t.me links on fash propaganda...
But yeah Telegram is not a fascist app, so it would be a bit much to block it entirely.

Have a good day :)
